### ISSUE TITLE
Unknown @ rule: @-moz-document.

### ISSUE THREAD

**Issue by FlandreDaisuki** [OpenUserCSS/openusercss.org#121]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| Save Theme | Stay in edit page and an error on editor |

## Steps to Reproduce the Problem

  1. Copy and paste my usercss [github-xp](https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/usercss/github-xp.user.css)
  1. Click **Save Theme**
  1. The error shown as following and can't save
      ![openusercss - openusercss - mozilla firefox_001](https://user-images.githubusercontent.com/5981459/41754806-a29c2c10-7606-11e8-9c59-ec3c31f48cc6.png)

## Environment details

  - Site version: 1.4.6
  - Browser and version: Firefox 61.0 (64 bit)
  - Installed extensions: brand new profile
  - Operating system: Linux Mint 18.3

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
導航至 https://openusercss.org/theme/edit
Content Security Policy: 頁面的設定阻擋了 self 的資源載入:（「script-src」）。 Source: call to eval() or related function blocked by CSP.
Can you hear me? app.76e121bd80c469113582.js:1:45875
There's nothing for you to see here, FlandreKawaii app.76e121bd80c469113582.js:1:45359
Listen. G4 E4 F4 D4  E4 C4 D4 A3  G3 F3 G3 A4 G4 app.76e121bd80c469113582.js:1:45743
TypeError: "can't convert undefined to object" vendor.421603000dcdc9541f2d.js:2:19473
    parseUserCSS https://openusercss.org/_nuxt/pages/theme/edit/_id.1124c91d37a6d1d0bb94.js:2:1644
    6et https://openusercss.org/_nuxt/vendor.421603000dcdc9541f2d.js:2:20087
    Qe https://openusercss.org/_nuxt/vendor.421603000dcdc9541f2d.js:2:19589 
Content Security Policy: 頁面的設定阻擋了 self 的資源載入:（「script-src」）。 Source: Call to eval() or related function blocked by CSP..
  ```
</details>

**Comment by Martii** [comment]
Safe to ignore that. CSS `@document` is scheduled at some point in CSS4 and was backed out of CSS3. The `-moz-` prefix means that it's Mozilla specific. See also https://developer.mozilla.org/docs/Web/CSS/@document

**Comment by FlandreDaisuki** [comment]
@Martii oh.. OK
But I can't save theme still. 😓

**Comment by Martii** [comment]
Well I'll give it a shot on my account temporarily... I'm new to the site as well. Good as any test to start. :) Please hold.

**Comment by Martii** [comment]
Hmmm I get a red popup that says something like:

``` console
Network error: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
```

Will probably have to wait for someone higher up to assist you as I can't upload your CSS successfully myself. 

However I did dump most of the script in between and it successfully did upload... so that to me would normally indicate you may have an error in the CSS somewhere... perhaps a mismatched curly brace, missing comma, missing semi-colon, or something else?

**Comment by Martii** [comment]
I think https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/usercss/github-xp.user.css#L274 is a variable... did you set it?

**Comment by FlandreDaisuki** [comment]
@Martii variable? It's a name of keyframes.
https://developer.mozilla.org/en-US/docs/Web/CSS/@keyframes

**Comment by Martii** [comment]
Well just guessing *(variables are my least known in CSS and I'm still getting used to the site :)*... after that "Clippy" block is where it refuses to let me upload it.

**Comment by Martii** [comment]
Should the line at https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/usercss/github-xp.user.css#L287 be `::after` instead of `:after`?

**Comment by Martii** [comment]
Ref:
* https://developer.mozilla.org/docs/Web/CSS/::after  *(some note about CSS2 vs CSS3)*... perhaps some validation is occurring that requires CSS3? *(taking another stab guess)*

**Comment by Martii** [comment]
Okay... so knocking out https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/usercss/github-xp.user.css#L296 and https://github.com/FlandreDaisuki/My-Browser-Extensions/blob/master/usercss/github-xp.user.css#L309 allows almost 100% to upload... won't make any more conclusions as this is a weird issue... but I would start looking at those data URI PNG's to see if there's an issue.

**Comment by FlandreDaisuki** [comment]
@Martii Yes, you're right.
I replace Data URL to imgur and it works!

**Comment by Martii** [comment]
I'm hoping this isn't a ReDoS issue in one of the packages that OUCSS utilizes but it seems like it or an overload of the CPU parsing. Glad you found a work-around for the moment.

**Comment by the-j0k3r** [comment]
> @Martii Yes, you're right.
> I replace Data URL to imgur and it works!

Theme size is key in OUCSS the data URI just add size and OUCSS doesnt take larger themes at all.

**Comment by Martii** [comment]
A better error response stating any limits reached would be much more helpful. Stabbing at a bug without knowing what tool to use is lengthy. All in time I suppose... the site is still Beta and we all must be patient. :)

**Comment by the-j0k3r** [comment]
The site maybe beta and half the bugs aren't even reported or the developer doesn't see some bugs because of lack of testing in other OS's and browser configs.

But nothing is ever bug free in my experience, so beta/alpha/stable to me just mean, alpha = expect loads of bugs/breakages, beta= expect some bugs and maybe the odd breakage, stable=expect the same as beta :)

**Comment by Martii** [comment]
> half the bugs aren't even reported

Hop to it! ;)

> because of lack of testing in other OS's and browser configs.

Hop faster! ;)

**Comment by the-j0k3r** [comment]
> Hop faster! ;)

Not my job. Im a user just like everyone else.

**Comment by Martii** [comment]
You do realize who you are talking to right?????????    I'm ........... the BATMAN! ;) 

Anyhow you are seriously going off-topic, and dragging me and everyone along with it. Rather than complain about something continue doing something about it e.g continue to test and report like a good clown instead of being passive-aggressive towards the owner. Ciao for now since I have sites to maintain myself, assisted a little with this issue since it peaked my interest, and have fun with your "pen". ;)

**Comment by the-j0k3r** [comment]
@Martii I want going to reply, bevause I hate dropping to any level of low, but your level of [douchebaggery descrip#3])https://www.urbandictionary.com/define.php?term=douchebaggery) has led me to ignore you completely because the level of douche hypocrisy in your reply exceed insanity +1.

**Comment by the-j0k3r** [comment]
@Martii I wast going to reply, because I hate dropping to any level of low, but your level of [douchebaggery descrip#3])https://www.urbandictionary.com/define.php?term=douchebaggery) has led me to ignore you completely because the level of douche hypocrisy in your reply exceed insanity +1. Goodbye troll.

**Comment by DecentM** [comment]
Thanks for the report!  
This error in the editor is safe to ignore, since it's unable to understand -moz-document rules (for now). It should still report warnings like usual.  

Please take care in the future to respect others' views, I don't want to lock threads and limit sharing ideas in the comments (yes, even the deleted ones). We're on GH to see new and interesting things, not to berate each other and mount our views on top of the site's morale.

**Comment by Martii** [comment]
@DecentM 
Clearly the the-j0k3r is not abiding by your advice and being beyond snarky. This will make me not interested in assisting anyone here both personally and professionally. I would recommend you locking topics. I'm considering a ban along with the report for this user.
