### ISSUE TITLE
Newest themes several issues - bad user experience.

### ISSUE THREAD

**Issue by the-j0k3r** [OpenUserCSS/openusercss.org#122]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
 What you expected the site to do | What the site actually did |
| Allow clicking of theme to goto that theme (and install OR see more info) | Cant click any of the newest themes to goto any of the themes |
| Show screenshots of newest themes | Newest themes have no way of showing screenshots see :asterisk: |
| Newest uploaded should take minutes to show in category | Newest uploaded take many hours to show in category |

As is, IMHO is the example of what not to do, the landing page that should show what themes look like and allow easy navigation to that theme page is non existent, the Newest themes are treated as second class.

## Steps to Reproduce the Problem

  1. open https://openusercss.org/
  1. see no screenshots on newest themes (the most important category is not important for OUCSS)
  1. Try to click any of the newest themes to goto that theme (and fail miserably)

:asterisk: Related to https://github.com/OpenUserCSS/openusercss.org/commit/ef2e93a444b25359719e553eb2b8ca0171e6bd7d#commitcomment-29377378

## Environment details

  - Site version: 1.4.6
  - Browser and version: 66.0.2
  - Installed extensions: Stylus
  - Operating system: Win 10 pro

----

<details>
  <summary><strong>Stack trace</strong> (click to expand)</summary>

  ```
  {{trace here}}
  ```
</details>

**Comment by DecentM** [comment]
Thanks for creating this issue out of the comments, as always! :upside_down_face:  
Not being able to click themes is actually fixed, but is waiting for a release.

**Comment by DecentM** [comment]
Newest themes not showing up immediately isn't a huge issue in my opinion, I think the cache should take the priority over everything being real-time, but shouldn't be hard to update the store once a theme gets published.

**Comment by the-j0k3r** [comment]
Let me just reason with myself out-loud, this isnt a rant FYI.

The priorities are, as a theme developer, to release themes over this or that platform to share with the widest audience possible ASAP your creation.

If an update is released to theme XYZ that fixes something, wouldn't it make sense to want update to reach the users also as fast as possible?

So now talking to you, seemingly dismissing this as not important for a website designed to host themes, somewhat a weird logic, sorry I dont understand,

Also the way the NEW themes are presented currently which got worst from version 1.0.1 forward.is secondary, to the long term already existing themes,

I see this as an issue combining with the long time to update/show up, this is not inviting to attract more creators IMO. If you dont have content you dont have a website.

My 2cents :0

**Comment by DecentM** [comment]
It would make sense that a theme author updates their theme as soon as a new version is finished, but I don't see your point here. The speed of how fast a theme developer updates their theme is entirely dependent on them. The site doesn't limit how fast you can update a theme by going through the editor.  

Design is something that can be reasonably quickly changed by editing the page template and/or CSS. As such, I'm aiming to create the necessary features *before* working on UX and looks. Don't get me wrong, UX is important, but there is no UX unless there is an app to be used. It's just how I personally order my tasks, but when everything is done, there will be a product that's functional and easy to use.  

What I'm trying to achieve is having fun while developing a useful site. Having to write this is neither of those. Because of this, there's no rush - as I mentioned before - and I'm not worried about the site becoming popular quite yet. I'd rather present a full app later than an incomplete one sooner.  

As far as I can tell, @Martii is not a troll at all (they author https://openuserjs.org/), and I'm appalled that you would try to use the amount of issues you created to help to denominate anybody like that. I appreciate the feedback, but at the same time, it's more important to keep moving forward and work together than get stuck on our differences.

I can't know the reason you've deleted some comments, but you were extremely rude in them towards your recipient. This is not what I stand for or should anybody in my opinion.  

I want to ask you to take a step back from GitHub and rethink what you want to achieve on the Internet in general over a few weeks. I realise this may look different on your end, but from everyone else's perspective, it looks like you've joined a project, then started attacking others because their opinion is different.

**Comment by the-j0k3r** [comment]
@DecentM please dont drag issues from other comments into unrelated topic/issues.

**Comment by DecentM** [comment]
I'm sorry, but I'm enfocing this by blocking you from OUC for a month. I really wish this hadn't come to this, but the fact you'd close an issue after I continue a locked topic is not acceptable at all.  

Take some time.

**Comment by DecentM** [comment]
Merged into https://github.com/OpenUserCSS/openusercss.org/issues/124
