### ISSUE TITLE
Logged out theme editor

### ISSUE THREAD

**Issue by Mottie** [OpenUserCSS/openusercss.org#132]
| Expected behaviour | Actual behaviour |
| ------------------ | ---------------- |
| What you expected the site to do | What the site actually did |
| Go to the main site page | Stay on theme editor |

## Steps to Reproduce the Problem

  1. Log out, if not already.
  1. Go to https://openusercss.org/theme/edit
  1. Wonder what would happen if I typed in a bunch of stuff...

## Environment details

  - Site version: 1.5.0
  - Browser and version: All browsers
  - Installed extensions: N/A
  - Operating system: Windows, but that shouldn't matter

----

**Comment by DecentM** [comment]
I deliberately did this, because if someone logs out while editing a theme, the theme would be lost if the site navigated away. If you try saving a theme while logged out, an error should pop up that says the session is invalid.  

I'll close this since this is the behaviour I want, but feel free to continue the discussion if you feel like you have a better solution in mind!
