### ISSUE TITLE
Unable to save my Userstyle

### ISSUE THREAD

**Issue by mikhoul** [OpenUserCSS/openusercss.org#148]
I'm using: 

Chromium | 68.0.3440.106 (Build officiel) (32 bits)
-- | --
Révision | 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}

Just opened an account to share a style with a friend but nothing happen when I click on the "Save Theme" button sadly.... 🤔 Maybe I'm missing something obvious... 

![image](https://user-images.githubusercontent.com/5678673/45240314-305d1a00-b2b6-11e8-8b57-cb8d95febf01.png)

Regards :octocat:

**Comment by DecentM** [comment]
Thanks for reporting!  
I need some additional info on your environment, since I can't reproduce this:  

- Confirm that you have a stable internet connection
- Your operating system
- Installed extensions

If that doesn't work, you can try using a different browser or a different device to see if it happens everywhere.

**Comment by mikhoul** [comment]
Chromium | 68.0.3440.106 (Build officiel) (32 bits)
-- | --
Révision | 1c32c539ce0065a41cb79da7bfcd2c71af1afe62-refs/branch-heads/3440@{#794}
Système d'exploitation | Windows 7
JavaScript | V8 6.8.275.26
Flash | 28.0.0.137

The only hint I have is that one time after trying again I've see a quick flash saying I need a verified email but I never received such email and yes I've looked in my spam folder and the same thing happen iwth or without extension.

Maybe you should put the quick message that we need to validate/check the email with a button to close the warning this way we should be able to see it. Also put some mechanism to resend the verification email too.

Regards :octocat:

**Comment by DecentM** [comment]
Ah, so you did get the red error message, that's good then.  
There's already a button in your account settings that resends the verification e-mail. Go to your profile, then click `Account`, then there will be a resend button in the left column.  

I'll close this, since the issue should be solved after this, but feel free to let me know if you still can't post anything after this.

**Comment by mikhoul** [comment]
@DecentM   Sadly it resolved nothing even after mt email was verified I can't save  my styles.

Also like I said there is NO MESSAGE that show and say we need to verify ou account with an email.

One time of 25 I've seen a quick flash during 1/100th of second with the message but I was lucky to see it. 

It should be a priority that users could **FULLY register** easily and  being able to save style. I'm pretty sure there is many other users that just give up after not being able to save their styles 😕.

At the very minimum I should see a message telling me why I can't save the style **before** I fulfill all the fields with description, screenshots etc.... 

Hree's a screncast: https://screencast-o-matic.com/watch/cFQbcOqsK5
