### ISSUE TITLE
Regarding the search

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#21]
The search seems to be very... needy shall I put it? It does well with spaces, capital letters and such, but if I am ONE LETTER OFF... Search for raitaro or decent, nothing comes up.

Also if I search `youtube` then `Youtube - Remove trending items` and `OpenUserCSS DeepDark` appear. Not sure why my theme shows up though. If I search `github` (git doesn't return anything btw) my theme also appears.

If I search for `DecentM` no themes show up even though in the users box you can clearly see `6 themes`.  On the other hand `RaitaroH` gives the expected results.

Also is the avatar image supposed to be cropped like that? Here is the avatar in full length:
![screenshot_20171230_153316](https://user-images.githubusercontent.com/19552720/34454659-8304c964-ed78-11e7-851f-2dff66fcfd2c.png)

**Comment by DecentM** [comment]
I agree that searching should be more leinient, but that would require some elaborate search backend, like Elasticsearch.

Your theme shows up for the youtube search query because the source code contains it. Theme properties are weighted this way:  

| Value | Weight |
| ------- | ---------- |
| title | 3 |
| description | 2 |
| source code | 1 |  
<br>
So for example, if a theme had youtube in the description, it will show up after the ones that have it in the title  

Same with the github query, you have it in the description of your theme.  
<br>
When you search for a username, items that contain that username will be returned, so you can view someone's themes after clicking on the user card in the results.  
<br>
Yes, that's how I solved some empty space, but I can take the argument that it's ugly. After theme ratings are implemented, it will become larger though to fit a newline.
