### ISSUE TITLE
Conainerise the development environment

### ISSUE THREAD

**Issue by QuentinCaffeino** [OpenUserCSS/openusercss.org#22]
Good day!

Could you please add information to readme how to start a docker container?

Happy holidays :)

**Comment by DecentM** [comment]
For development, running in a container isn't necessary. To test building, you should be able to run `docker build .`
At some point, I want to take a day to write tons of documentation about setting up a development environment though, this would be included in there.

Thanks, to you as well!

I'll close this for now, but feel free to comment if you want.

**Comment by QuentinCaffeino** [comment]
I run about 75% of projects in containers cause I don't want to install all tools on my pc :)
Of course I tried to build. But failed on 8'th line cause build folder doesn't exist on first run)
Why do you need such complicated environment. Is it some special architecture? You could run any env (dev, prod, ...) using one docker-compose config and little setup in entry script.
I would be great if you could explain structure you use in a few words.
If you want I could share architecture I use for modular services)

**Comment by DecentM** [comment]
Ah, I see. I agree that there should be a simpler pipeline.
The environment is complicated because I built it organically over time that I was working on the site over the last few months.
I'm planning on overhauling the development process after the MVP is complete (switching to Webpack, containerising the whole development and testing process. This will come with the benefit of having the same environment in development as in production.

I've edited the title of this issue so that I can put it on the roadmap.

**Comment by DecentM** [comment]
Oh, I forgot to mention. Every binary that's needed to develop is in `node_modules/.bin`, there shouldn't be anything needed to be installed globally to run the application.

**Comment by DecentM** [comment]
@QuentinCaffeino I'm finally getting to the issues in this range. Can you see if you can start the app with the start script?

**Comment by QuentinCaffeino** [comment]
Sure, I'll try this evening :)

**Comment by QuentinCaffeino** [comment]
What do I have to run? Cause I get errors if I run `setup.sh`. Overall your naming looks kinda strange. May I ask why do you name this files like this: dev.dockerfile, dev.stack.yml?

`setup.sh` fails with:
```
./start.sh: 25: read: Illegal option -n
```
Next problem is:
```
./start.sh: 32: ./start.sh: Syntax error: "(" unexpected
```

I run bash:
```shell
$ bash --version
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
```

**Comment by DecentM** [comment]
You should run `start.sh`.  Also make sure that you run it with `./start.sh` and not `bash ./start.sh`, because the script is not written for bash.  
The naming convention is this way because there are going to be more container groups for different tasks, as well as separate development and production images.

**Comment by QuentinCaffeino** [comment]
Well actually if I start it with `./start.sh` errors happen. But when I run it with bash it runs ok. [Proof](https://i.imgur.com/bM1dQlN.png)
Yeah, I get it with `dev` in names. But why do you use `dev.stack.yml` instead of `dev.docker-compose.yml`?
Also you still can name `dev` configuration as `docker-compose.yml` and production as `prod.docker-compose.yml` so that you have need to use startup script only on server.

**Comment by DecentM** [comment]
I've added checks to the startscript. Can you check to see if the same issues are still there?  
I named it that way because it's faster to type, since you need to type the filename if it's not named `docker-compose.yml`, but it's all handled by the script anyway.

**Comment by DecentM** [comment]
I'll close this because I think I've fixed the issue, but feel free to let me know if it's still not working for you!
