### ISSUE TITLE
Forum recent topics duplicates

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#27]
Ahm, not sure if it looks like this because there are just so few things in the forum but to me it seems like every section has duplicates:
![image](https://user-images.githubusercontent.com/19552720/34461214-a21a1eac-ee2d-11e7-9a15-08b6498c0578.png)

**Comment by DecentM** [comment]
Yeah, it's multiplied four times for me when I go to /recent.
Every section has a different forum category at the bottom though. This isn't really a huge issue, but NodeBB does have an update available.

I'll upgrade it the day tomorrow, so that there's a backup of the stuff I did today (**everything** on the server is backed up each night)

**Comment by DecentM** [comment]
Fixed by `display: none`-ing all elements but the first
