### ISSUE TITLE
Installed themes

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#32]
The install button should change to `Installed` after you install a theme. Or maybe `Reinstall` or something like that.

**Comment by DecentM** [comment]
The site doesn't have access to Stylus at this point, so there is no reliable way to find out if a theme has been installed.

Further down the line (think "about a month"), after the core features are out of the way, I want to start talking with the guys making the extension about some sort of message bus between the site client and the extension. This will also make it possible to display a warning if the extension isn't installed.

I'll close this for now, because there's no way right now that this can be done, but feel free to add further ideas!
