### ISSUE TITLE
Multiple instances of the same theme

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#59]
I clicked the save button a few times because it wasn't saving. Now I got duplicates:
![image](https://user-images.githubusercontent.com/19552720/34734876-13b7d1c2-f576-11e7-8088-521fd247177d.png)

They also have different urls, so it is not a display problem:
https://openusercss.org/theme/5a54ff4c1bf0fd0b00422acc
https://openusercss.org/theme/5a54ff591bf0fd0b00422ace
https://openusercss.org/theme/5a54ff501bf0fd0b00422acd
https://openusercss.org/theme/5a54ff5b1bf0fd0b00422acf
https://openusercss.org/theme/5a54ff651bf0fd0b00422ad0

Do you want me to keep the duplicates?

**Comment by DecentM** [comment]
Did this happen while creating a new theme, or while editing an existing one?

**Comment by RaitaroH** [comment]
Creating.

**Comment by RaitaroH** [comment]
Maybe clicking on the save buttons multiple times made this happen?

**Comment by RaitaroH** [comment]
I deleted the other themes. They were annoying to look at.

**Comment by DecentM** [comment]
Yeah, when you're creating a new theme, saving it assumes it's new. I don't think there's a way to check if the theme being saved is new without the risk of overwriting your other themes.

I'll close this, because it's working as intended. If this happens again, please open a new issue and take a screenshot of the developer console if something pops up.

**Comment by RaitaroH** [comment]
Yeah, sure.
