### ISSUE TITLE
Help page doesn't notice stylus being installed

### ISSUE THREAD

**Issue by RaitaroH** [OpenUserCSS/openusercss.org#68]
![image](https://user-images.githubusercontent.com/19552720/34755709-8e8b8666-f5ce-11e7-8679-30c6aac49f9b.png)
Same thing on Firefox and Waterfox.

**Comment by DecentM** [comment]
I've already pushed the feature, but it won't actually work until https://github.com/openstyles/stylus/pull/328 is merged, which is pretty close to completion.

**Comment by DecentM** [comment]
The PR was merged, so you should be seeing this work as soon as Stylus is updated through the extension store of your browser :tada:

**Comment by maxigaz** [comment]
I'm using the latest stable version of Stylus that's available in AMO (1.3.9) and I can see the same message on the Help page using Firefox 59.0.1. Installing styles works flawlessly, though.

**Comment by DecentM** [comment]
Thanks for the feedback!  
It looks like the content script doesn't run on Firefox for some reason. I'm running 1.3.9 on Chromium, which works. Installing themes should always work because of the progressive design. If you really fell like it, feel free to open an issue on the Stylus repo, and either I or another contributor can take a look.
