### ISSUE TITLE
Screenshot Thumbnails

### ISSUE THREAD

**Issue by hyperfekt** [OpenUserCSS/openusercss.org#85]
An essential feature for browsing themes is to be able to see at a glance whether they appeal to the user without having to click through to the theme's page.
This means a small version of the main screenshot should be displayed next to every theme on every overview of themes.
The following is required to make this work well:
- [ ] Caching images on the proxy to guarantee quick loading
- [ ] Limiting user-facing image size for quick loading (this is already done when giving the proxy a size parameter, and should be extended to the individual theme pages as well)

**Comment by DecentM** [comment]
This is just a matter of design, since the main OpenUserCSS website already uses an image proxy. Specifically, this one: https://github.com/willnorris/imageproxy  
I'd be happy to take design recommendations if you want to have a go. I currently use the [Pencil project](https://pencil.evolus.vn/) for that. Of course, feel free to use any design tool you'd like, just the export format should be in a commonly openable file format (png, svg, etc...)

**Comment by hyperfekt** [comment]
I checked beforehand and the image proxy as currently configured does not fulfill either of the two stated requirements. Given a URL with redirects it will introduce considerable latency, and given a large image it will serve an image just as large on individual theme pages.

**Comment by DecentM** [comment]
I mean, proxy or no proxy, a redirecting URL will cause delays.  
I'm not sure what you mean by it not fulfilling either caching or compressing images (I assume that's what you mean). The proxy is configured to hold images on the SSD storage for a few days.  
I just tested and [this 1.2MB image](https://upload.wikimedia.org/wikipedia/commons/e/e0/Large_Scaled_Forest_Lizard.jpg) comes out [resized under 154KB](https://imageproxy.openusercss.org/x0.15/https://upload.wikimedia.org/wikipedia/commons/e/e0/Large_Scaled_Forest_Lizard.jpg).

**Comment by hyperfekt** [comment]
Indeed, because you are using the appropriate URL to instruct the proxy to do so. Removing the x0.15 parameter maintains the original image dimensions, but also the original file size. The aim is to serve small file sizes for screenshots, which is currently not done, as there is no additional parameter passed to the image proxy for those.
Asking users to provide a URL for images to load from will inevitably lead to these URLs pointing to some very slow (or redirecting) hosts, and the image proxy currently always performs one such slow request before serving the image, alas caching in the sense that I understand it appears to be inoperable.

**Comment by DecentM** [comment]
When a screenshot is displayed, the client automatically creates a small and a large version of the image. The small one is shown while the large one is loading. Any and all network requests are also cached by the active service worker as well, so I'm not that worried about screenshot performance currently.  
An alternative to proxying supplied URLs would be to make uploading screenshots possible. Unfortunately, this is out of the question for now, because the server is on a lower tier VPS with not that much storage.

**Comment by DecentM** [comment]
Fixed this in the v1.0.0 branch, it will be rolling out when that's complete :tada:
