### ISSUE TITLE
Cant' search

### ISSUE THREAD

**Issue by tkosamja** [OpenUserCSS/openusercss.org#88]
When I try to search I get the following error (and if I keep pressing "Search" the following happens LOL)

![capture](https://user-images.githubusercontent.com/26143003/38778502-80d2ff66-40b2-11e8-9b1a-6a54b788af17.PNG)

**Comment by DecentM** [comment]
Thanks for the feedback!
This is already being tracked in https://github.com/OpenUserCSS/openusercss.org/issues/67, please follow that for updates.
In the meantime, you can use the `Search on Google` button as the note above the search field indicates.  

Since every search query returns an error, all of them have to be shown because you might have changed the query since the last one. I'm certain the error is caused by some property of a theme.
